#!/usr/bin/env sh
set -e
HERE="$(dirname "$(readlink -f "$0")")"
BINARY_PATH="$HERE/usr/bin/webshard_editor"
for loader in \
  /lib64/ld-linux-x86-64.so.2 \
  /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 \
  /lib/ld-linux-x86-64.so.2; do
  if [ -x "$loader" ]; then
    exec "$loader" --library-path "$HERE/usr/lib:$HERE/usr/lib64:$LD_LIBRARY_PATH" "$BINARY_PATH" "$@"
  fi
done
exec "$BINARY_PATH" "$@"
