#[cfg(feature = "code_editor")]
use egui_code_editor::Syntax;
#[cfg(feature = "code_editor")]
use std::collections::BTreeSet;

#[cfg(feature = "code_editor")]
pub fn wgsl() -> Syntax {
    let keywords: BTreeSet<&str> = BTreeSet::from_iter(vec![
        // Control flow
        "fn",
        "let",
        "var",
        "const",
        "override",
        "struct",
        "return",
        "if",
        "else",
        "switch",
        "case",
        "default",
        "loop",
        "break",
        "continue",
        "while",
        "for",
        "discard",
        "enable",
        "requires",
        "continuing",
        "fallthrough",
        // Type qualifiers
        "bitcast",
        "alias",
    ]);

    let types: BTreeSet<&str> = BTreeSet::from_iter(vec![
        // Scalar types
        "bool",
        "i32",
        "u32",
        "f32",
        "f16",
        // Vector types
        "vec2",
        "vec3",
        "vec4",
        "vec2i",
        "vec3i",
        "vec4i",
        "vec2u",
        "vec3u",
        "vec4u",
        "vec2f",
        "vec3f",
        "vec4f",
        "vec2h",
        "vec3h",
        "vec4h",
        // Matrix types
        "mat2x2",
        "mat2x3",
        "mat2x4",
        "mat3x2",
        "mat3x3",
        "mat3x4",
        "mat4x2",
        "mat4x3",
        "mat4x4",
        "mat2x2f",
        "mat2x3f",
        "mat2x4f",
        "mat3x2f",
        "mat3x3f",
        "mat3x4f",
        "mat4x2f",
        "mat4x3f",
        "mat4x4f",
        "mat2x2h",
        "mat2x3h",
        "mat2x4h",
        "mat3x2h",
        "mat3x3h",
        "mat3x4h",
        "mat4x2h",
        "mat4x3h",
        "mat4x4h",
        // Container types
        "array",
        "ptr",
        "atomic",
        // Sampler types
        "sampler",
        "sampler_comparison",
        // Texture types
        "texture_1d",
        "texture_2d",
        "texture_2d_array",
        "texture_3d",
        "texture_cube",
        "texture_cube_array",
        "texture_multisampled_2d",
        "texture_external",
        "texture_storage_1d",
        "texture_storage_2d",
        "texture_storage_2d_array",
        "texture_storage_3d",
        "texture_depth_2d",
        "texture_depth_2d_array",
        "texture_depth_cube",
        "texture_depth_cube_array",
        "texture_depth_multisampled_2d",
    ]);

    let special: BTreeSet<&str> = BTreeSet::from_iter(vec![
        // Attributes
        "@vertex",
        "@fragment",
        "@compute",
        "@group",
        "@binding",
        "@location",
        "@builtin",
        "@interpolate",
        "@id",
        "@workgroup_size",
        "@align",
        "@size",
        "@must_use",
        "@const",
        "@diagnostic",
        "@invariant",
        // Address spaces
        "function",
        "private",
        "workgroup",
        "uniform",
        "storage",
        // Access modes
        "read",
        "write",
        "read_write",
        // Texture formats
        "rgba8unorm",
        "rgba8snorm",
        "rgba8uint",
        "rgba8sint",
        "rgba16uint",
        "rgba16sint",
        "rgba16float",
        "r32uint",
        "r32sint",
        "r32float",
        "rg32uint",
        "rg32sint",
        "rg32float",
        "rgba32uint",
        "rgba32sint",
        "rgba32float",
        "bgra8unorm",
        // Interpolation
        "perspective",
        "linear",
        "flat",
        "center",
        "centroid",
        "sample",
        // Builtin functions - Math
        "abs",
        "acos",
        "acosh",
        "asin",
        "asinh",
        "atan",
        "atan2",
        "atanh",
        "ceil",
        "clamp",
        "cos",
        "cosh",
        "countLeadingZeros",
        "countOneBits",
        "countTrailingZeros",
        "cross",
        "degrees",
        "determinant",
        "distance",
        "dot",
        "exp",
        "exp2",
        "extractBits",
        "faceForward",
        "firstLeadingBit",
        "firstTrailingBit",
        "floor",
        "fma",
        "fract",
        "frexp",
        "inverseBits",
        "inverseSqrt",
        "ldexp",
        "length",
        "log",
        "log2",
        "max",
        "min",
        "mix",
        "modf",
        "normalize",
        "pow",
        "quantizeToF16",
        "radians",
        "reflect",
        "refract",
        "reverseBits",
        "round",
        "saturate",
        "sign",
        "sin",
        "sinh",
        "smoothstep",
        "sqrt",
        "step",
        "tan",
        "tanh",
        "transpose",
        "trunc",
        // Builtin functions - Logical
        "all",
        "any",
        "select",
        // Builtin functions - Texture
        "textureDimensions",
        "textureGather",
        "textureGatherCompare",
        "textureLoad",
        "textureNumLayers",
        "textureNumLevels",
        "textureNumSamples",
        "textureSample",
        "textureSampleBias",
        "textureSampleCompare",
        "textureSampleCompareLevel",
        "textureSampleGrad",
        "textureSampleLevel",
        "textureSampleBaseClampToEdge",
        "textureStore",
        // Builtin functions - Atomic
        "atomicLoad",
        "atomicStore",
        "atomicAdd",
        "atomicSub",
        "atomicMax",
        "atomicMin",
        "atomicAnd",
        "atomicOr",
        "atomicXor",
        "atomicExchange",
        "atomicCompareExchangeWeak",
        // Builtin functions - Data packing/unpacking
        "pack4x8snorm",
        "pack4x8unorm",
        "pack2x16snorm",
        "pack2x16unorm",
        "pack2x16float",
        "unpack4x8snorm",
        "unpack4x8unorm",
        "unpack2x16snorm",
        "unpack2x16unorm",
        "unpack2x16float",
        // Builtin functions - Synchronization
        "storageBarrier",
        "workgroupBarrier",
        "workgroupUniformLoad",
        // Builtin functions - Derivative
        "dpdx",
        "dpdxCoarse",
        "dpdxFine",
        "dpdy",
        "dpdyCoarse",
        "dpdyFine",
        "fwidth",
        "fwidthCoarse",
        "fwidthFine",
        // Builtin values
        "position",
        "vertex_index",
        "instance_index",
        "front_facing",
        "frag_depth",
        "sample_index",
        "sample_mask",
        "local_invocation_id",
        "local_invocation_index",
        "global_invocation_id",
        "workgroup_id",
        "num_workgroups",
        // Constants
        "true",
        "false",
    ]);

    Syntax {
        language: "WGSL",
        case_sensitive: true,
        comment: "//",
        comment_multiline: ["/*", "*/"],
        hyperlinks: BTreeSet::new(),
        keywords,
        types,
        special,
    }
}
