// Converted from Shadertoy GLSL to WGSL
// Auto-generated by shadertoy_converter.rs

struct Uniforms {
    time: f32,
    audio_bass: f32,
    audio_mid: f32,
    audio_high: f32,
    resolution: vec2<f32>,
    _pad0: vec2<f32>,
}

@group(0) @binding(0)
var<uniform> uniforms: Uniforms;

struct VSOut {
    @builtin(position) pos: vec4<f32>,
    @location(0) uv: vec2<f32>,
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> VSOut {
    var out: VSOut;
    let x = f32((vertex_index & 1u) << 1u);
    let y = f32((vertex_index & 2u));
    out.pos = vec4<f32>(x * 2.0 - 1.0, 1.0 - y * 2.0, 0.0, 1.0);
    out.uv = vec2<f32>(x, y);
    return out;
}


// Example Shadertoy shader - Rainbow plasma
@fragment
fn fs_main(in: VSOut) -> @location(0) vec4<f32>
{
    let uv = in.uv * uniforms.resolution/uniforms.resolution;
    let col = 0.5 + 0.5*cos(uniforms.time+uv.xyx+vec3<f32>(0,2,4));
    return vec4<f32>(col,1.0);
}
